copyright/licensing update

diff --git a/so-elastic-reindex b/so-elastic-reindex
--- a/so-elastic-reindex
+++ b/so-elastic-reindex
@@ -1,5 +1,27 @@
 #!/bin/bash
-. /usr/sbin/so-elastic-common
+
+# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
+
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+COMMON="/usr/sbin/so-common"
+if ! [ -f $COMMON ]; then
+	echo "$COMMON not found."
+	echo "This script requires Security Onion Elastic Stack Release Candidate 2 (14.04.5.8 ISO) or later."
+	exit
+fi
+source $COMMON
 
 SKIP=0
 
